# Generated by Django 4.0.3 on 2022-04-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_reg_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_reg',
            name='image',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='employee_reg',
            name='address',
            field=models.TextField(),
        ),
    ]
