# Generated by Django 4.0.3 on 2022-04-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_reg_image_alter_employee_reg_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_reg',
            old_name='image',
            new_name='pic',
        ),
    ]
